#!/usr/bin/env bash

echo '
=== Worker post-receive hook ===
'

echo '
-----> Doing some git magic
'
# The actual update
GIT_WORK_TREE=/home/ubuntu/apps/lift/ git checkout -f

echo '
-----> Updating Requirements
'
sudo su -c "source /home/ubuntu/.virtualenvs/lift/bin/activate; pip install -r /home/ubuntu/apps/lift/requirements.txt" -s /bin/bash ubuntu

echo '
-----> Restarting Worker
'
sudo supervisorctl restart LiftCeleryWorker
sudo supervisorctl restart Beat
sudo supervisorctl restart Celerycam